version: '3'
services:
  tomcat:
    image: tomcat:9.0.75
    container_name: tomcat
    restart: on-failure
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - "/home/felix/IdeaProjects/week3/target:/usr/local/tomcat/webapps"
    networks:
      - week3

  database:
    image: postgres
    container_name: week3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: week3
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - week3

networks:
  week3:
    driver: bridge